<?php
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

if (isset($_GET['lang']) && in_array($_GET['lang'], ['es', 'fr'])) {
    $_SESSION['lang'] = $_GET['lang'];
}

$lang = $_SESSION['lang'] ?? 'es';

$translations = [
    'es' => [
        'dashboard' => 'Dashboard',
        'welcome' => 'Bienvenido',
        'personal_space' => 'Tu espacio personal del curso Python.',
        'logout' => 'Cerrar sesión',
        'view_course' => 'Ver el curso',
        'view_course_desc' => 'Acceder a todos los capítulos del curso de Python.',
        'practices' => 'Prácticas',
        'practices_desc' => 'Resolver ejercicios por capítulos con soluciones.',
        'progress' => 'Progreso',
        'progress_desc' => 'Aquí mostraremos pronto tu progreso guardado en MySQL.',
        'summary' => 'Resumen',
        'connected_user' => 'Usuario conectado',
        'course' => 'Curso',
        'python_basic' => 'Python básico',
        'status' => 'Estado',
        'active_account' => 'Cuenta activa',
        'language' => 'Idioma',

        'course_complete' => 'Curso completo',
        'learn_python_zero' => 'Aprender Python desde cero',
        'course_intro_desc' => 'Curso estructurado por capítulos con ejemplos claros y progresivos.',
        'go_practice' => 'Ir a prácticas',
        'back_dashboard' => 'Dashboard',

        'intro' => 'Introducción',
        'installation' => 'Instalación',
        'hello_world' => 'Hola mundo',
        'variables_types' => 'Variables y tipos',
        'input_output' => 'Input y output',
        'operators' => 'Operadores',
        'conditions' => 'Condiciones',
        'loops' => 'Bucles',
        'lists' => 'Listas',
        'tuples_dicts' => 'Tuplas y diccionarios',
        'functions' => 'Funciones',
        'strings' => 'Strings',
        'text_files' => 'Archivos de texto',
        'json_intro' => 'JSON',
        'errors_exceptions' => 'Errores y excepciones',
        'modules' => 'Módulos',
        'oop' => 'Programación orientada a objetos',
        'mini_project' => 'Mini proyecto',

        'intro_text' => 'Python es un lenguaje fácil de leer, potente y muy utilizado. Sirve para automatización, desarrollo web, inteligencia artificial, scripts, ciencia de datos y mucho más.',
        'installation_text' => 'Instala Python y comprueba que funciona correctamente en la terminal.',
        'hello_world_text' => 'El primer programa tradicional muestra un mensaje por pantalla.',
        'variables_text' => 'Las variables permiten guardar datos. Python detecta el tipo automáticamente.',
        'input_output_text' => 'Con input() pides datos al usuario y con print() los muestras.',
        'loops_for' => 'For',
        'loops_while' => 'While',

        'site_title' => 'Curso Python',
        'login' => 'Iniciar sesión',
        'register' => 'Registrarse',
        'hero_badge' => 'Aprende programando',
        'hero_title' => 'Aprende Python paso a paso con una plataforma clara y práctica',
        'hero_desc' => 'Sigue el curso, resuelve ejercicios directamente en la web, realiza quizzes con temporizador y entrega tus proyectos en un entorno pensado para avanzar de forma progresiva.',
        'start_now' => 'Empezar ahora',
        'already_account' => 'Ya tengo cuenta',

        'chapters_count' => 'Capítulos del curso',
        'exercises_count' => 'Ejercicios prácticos',
        'quizzes_count' => 'Quizzes por capítulo',

        'student_dashboard' => 'Dashboard del alumno',
        'course_progress' => 'Progreso del curso',
        'general_progress' => 'Progreso general',
        'exercises_label' => 'Ejercicios',
        'quizzes_label' => 'Quizzes',
        'average_grade' => 'Nota media',
        'next_goal' => 'Próximo objetivo',
        'next_goal_text' => 'Completar el capítulo 10 y enviar la siguiente entrega',

        'features_badge' => 'Qué ofrece la plataforma',
        'features_title' => 'Todo en un solo lugar',
        'features_desc' => 'Una experiencia clara para estudiar, practicar, evaluarse y seguir el progreso.',
        'feature_course' => 'Curso guiado',
        'feature_course_desc' => 'Contenido organizado por capítulos para aprender de forma progresiva.',
        'feature_exercises' => 'Ejercicios prácticos',
        'feature_exercises_desc' => 'Resuelve ejercicios directamente desde la plataforma y guarda tu progreso.',
        'feature_quizzes' => 'Quizzes automáticos',
        'feature_quizzes_desc' => 'Evalúate con temporizador, corrección automática y nota final inmediata.',
        'feature_projects' => 'Proyectos y deberes',
        'feature_projects_desc' => 'Entrega archivos, sigue el calendario y consolida lo aprendido.',

        'cta_title' => 'Empieza hoy tu progreso en Python',
        'cta_desc' => 'Crea tu cuenta, accede al contenido del curso y empieza a practicar desde el primer día.',
        'create_account' => 'Crear cuenta',
        'account_status' => 'Estado',

        'user_id_not_found' => 'No se encontró el ID del usuario en la sesión.',
        'no_grade' => 'Sin nota',
        'no_activity_recorded' => 'Sin actividad registrada',
        'dashboard_load_error' => 'Error al cargar el dashboard',

        'progress_message_100' => '¡Curso completado! Ahora toca consolidar todo con el proyecto final.',
        'progress_message_75' => 'Muy buen avance. Ya estás en la recta final del curso.',
        'progress_message_50' => 'Buen progreso. Sigue así para llegar al proyecto con confianza.',
        'progress_message_start' => 'Buen comienzo. Sigue avanzando poco a poco.',

        'progress_dashboard' => 'Dashboard de progreso',
        'python_basic_progress' => 'Tu avance en Python básico',
        'completed_exercises_count' => '%d de %d ejercicios completados',
        'course_completed' => 'Curso completado',
        'project_submissions_done' => 'Entregas hechas (proyecto)',

        'completed_exercises' => 'Ejercicios completados',
        'out_of_total' => 'De un total de %d',
        'pending_submissions_project' => 'Entregas pendientes (proyecto)',
        'pending_to_send_or_complete' => 'Pendientes por enviar o completar',
        'active' => 'Activo',
        'account_enabled_to_continue' => 'Cuenta habilitada para continuar',
        'current_course' => 'Curso actual',
        'course_foundations_final_project' => 'Fundamentos + proyecto final',

        'quick_access' => 'Accesos rápidos',
        'my_homework' => 'Mis deberes',
        'my_homework_desc' => 'Ver enunciados y subir entregas en ZIP.',
        'my_projects' => 'Mis proyectos',
        'my_projects_desc' => 'Ver las entregas del proyecto y subir archivos.',
        'quizzes' => 'Quizzes',
        'quizzes_desc' => 'Realiza quizzes por capítulo con temporizador y nota automática.',

        'pending' => 'Pendientes',
        'pending_submissions_count' => '%d entregas',
        'profile' => 'Perfil',
        'open_menu' => 'Abrir menú',
        'user_not_identified' => 'Usuario no identificado.',
        'user_not_found' => 'Usuario no encontrado.',

        'name_email_required' => 'El nombre y el email son obligatorios.',
        'invalid_email' => 'El email no es válido.',
        'email_already_used' => 'Ese email ya está siendo usado por otro usuario.',
        'fill_three_password_fields' => 'Para cambiar la contraseña debes completar los tres campos.',
        'password_confirmation_mismatch' => 'La nueva contraseña y la confirmación no coinciden.',
        'password_min_length' => 'La nueva contraseña debe tener al menos 6 caracteres.',
        'current_password_incorrect' => 'La contraseña actual no es correcta.',
        'profile_updated_successfully' => 'Perfil actualizado correctamente.',
        'profile_update_error' => 'Error al actualizar el perfil',

        'my_profile' => 'Mi perfil',
        'account' => 'Cuenta',
        'profile_update_desc' => 'Aquí puedes actualizar tus datos personales y tu contraseña.',
        'edit_profile' => 'Editar perfil',
        'name' => 'Nombre',
        'email' => 'Email',
        'change_password' => 'Cambiar contraseña',
        'leave_password_blank' => 'Deja estos campos vacíos si no quieres cambiar la contraseña.',
        'current_password' => 'Contraseña actual',
        'new_password' => 'Nueva contraseña',
        'confirm_new_password' => 'Confirmar nueva contraseña',
        'save_changes' => 'Guardar cambios',

        'account_information' => 'Información de la cuenta',
        'current_name' => 'Nombre actual',
        'current_email' => 'Email actual',
        'role' => 'Rol',
        'member_since' => 'Miembro desde',

        'tip' => 'Consejo',
        'profile_security_tip' => 'Usa una contraseña segura y un email al que tengas acceso, para no perder tu cuenta.',
        'projects_page_desc' => 'Trabajos largos con varias entregas secuenciales.',
        'teacher' => 'Profesor',
        'created' => 'Creado',
        'view_project' => 'Ver proyecto',
        'no_projects_available' => 'No hay proyectos disponibles todavía.',
        'student' => 'Estudiante',
        'user_not_identified' => 'Usuario no identificado.',
        'chapter' => 'Capítulo',
        'hello_user' => 'Hola',
        'total' => 'Total',
        'completed' => 'Completados',
        'pending_lower' => 'pendiente',
        'open' => 'Abrir',
        'quizzes_by_chapter' => 'Quizzes por capítulo',
        'quiz_progress_text' => 'aquí puedes evaluar tu progreso.',
        'chapter_quiz_default_desc' => 'Quiz del capítulo.',
        'duration' => 'Duración',
        'best_grade' => 'Mejor nota',
        'no_attempt' => 'Sin intento',
        'start_quiz' => 'Empezar quiz',
        'invalid_quiz' => 'Quiz no válido.',
        'quiz_not_found' => 'Quiz no encontrado.',
        'quiz_no_questions' => 'Este quiz no tiene preguntas todavía.',
        'remaining_time' => 'Tiempo restante',
        'question' => 'Pregunta',
        'submit_quiz' => 'Entregar quiz',
        'admin_dashboard' => 'Admin Dashboard',
        'admin_panel' => 'Panel administrador',
        'admin_panel_desc' => 'Gestiona estudiantes, capítulos, deberes, proyectos y el progreso del curso.',
        'student_panel' => 'Panel estudiante',

        'students' => 'Estudiantes',
        'approved' => 'aprobados',
        'chapters' => 'Capítulos',
        'visible_plural' => 'visibles',
        'homework_projects' => 'Deberes y proyectos',
        'homework' => 'deberes',
        'projects' => 'proyectos',
        'submissions_progress' => 'Entregas / progreso',
        'progress_records' => 'registros de progreso',

        'manage_chapters' => 'Gestionar capítulos',
        'manage_chapters_desc' => 'Crear, editar, ordenar y activar capítulos visibles.',
        'manage_homework' => 'Gestionar deberes',
        'manage_homework_desc' => 'Crear deberes y revisar entregas de los alumnos.',
        'manage_projects' => 'Gestionar proyectos',
        'manage_projects_desc' => 'Administrar proyectos y sus entregas.',
        'manage_quiz' => 'Gestionar quiz',
        'manage_quiz_desc' => 'Administrar preguntas y actividades por capítulo.',

        'pending_registrations' => 'Inscripciones pendientes',
        'pending_count_suffix' => 'pendiente(s)',
        'date' => 'Fecha',
        'actions' => 'Acciones',
        'no_pending_registrations' => 'No hay inscripciones pendientes.',
        'approve' => 'Aprobar',
        'reject' => 'Rechazar',
        'confirm_reject_registration' => '¿Seguro que quieres rechazar esta inscripción?',

        'latest_students' => 'Últimos estudiantes',
        'no_registered_students' => 'No hay estudiantes registrados.',
        'pending_status' => 'Pendiente',
        'rejected' => 'Rechazado',

        'chapters_summary' => 'Resumen de capítulos',
        'order' => 'Orden',
        'title_es' => 'Título ES',
        'title_fr' => 'Título FR',
        'visible' => 'Visible',
        'no_chapters_yet' => 'No hay capítulos todavía.',
        'yes' => 'Sí',
        'no' => 'No',
        'invalid_chapter' => 'Capítulo inválido.',
        'invalid_visibility_value' => 'Valor de visibilidad inválido.',
        'visibility_updated' => 'Visibilidad actualizada.',
        'chapter_deleted' => 'Capítulo eliminado.',

        'chapters_list_desc' => 'Lista de capítulos del curso.',
        'new_chapter' => 'Nuevo capítulo',
        'code' => 'Código',
        'edit' => 'Editar',
        'deactivate' => 'Desactivar',
        'activate' => 'Activar',
        'delete' => 'Eliminar',
        'confirm_delete_chapter' => '¿Seguro que quieres eliminar este capítulo?',
        'homework_desc' => 'Crea deberes y publica enunciados para tus estudiantes.',
        'create_homework' => 'Crear un deber',
        'homework_required_fields' => 'El título y el enunciado son obligatorios.',
        'homework_created' => 'Deber creado correctamente.',

        'title' => 'Título',
        'statement' => 'Enunciado',
        'deadline' => 'Fecha límite',
        'create_homework_btn' => 'Crear deber',

        'published_homework' => 'Deberes publicados',
        'no_deadline' => 'Sin fecha límite',

        'view_submissions' => 'Ver entregas',
        'confirm_delete_homework' => '¿Eliminar este deber y todas las entregas?',
        'no_homework_yet' => 'No hay deberes todavía.',
        'project_required_fields' => 'El título y la descripción son obligatorios.',
        'project_created' => 'Proyecto creado correctamente.',
        'projects_admin_desc' => 'Crea proyectos formados por varias entregas secuenciales.',
        'create_project' => 'Crear un proyecto',
        'project_title' => 'Título del proyecto',
        'project_title_placeholder' => 'Ejemplo: Proyecto final Python',
        'description' => 'Descripción',
        'project_description_placeholder' => 'Describe el proyecto, objetivos, requisitos, etc.',
        'create_project_btn' => 'Crear proyecto',
        'created_projects' => 'Proyectos creados',
        'view_documentation' => 'Ver documentación',
        'manage_submissions' => 'Gestionar entregas',
        'no_projects_yet' => 'No hay proyectos todavía.',
        'projects_dashboard' => 'Dashboard de proyectos',
        'projects_dashboard_desc' => 'Vista general de proyectos, fases y correcciones pendientes.',
        'no_projects_created_yet' => 'Todavía no hay proyectos creados.',
        'pending_count_badge' => '%d pendiente(s)',
        'no_pending' => 'Sin pendientes',
        'phases' => 'Fases',
        'received_submissions' => 'Entregas recibidas',
        'corrected' => 'Corregidas',
        'released' => 'Liberadas',
        'pending_corrections' => 'Pendientes de corrección',
        'manage_phases' => 'Gestionar fases',
        'edit_project' => 'Editar proyecto',
        'view_corrections' => 'Ver correcciones',
        'role_not_allowed' => 'Rol no permitido.',
        'invalid_project' => 'Proyecto no válido.',
        'project_not_found' => 'Proyecto no encontrado.',

        'project_with_deliveries' => 'Proyecto con entregas secuenciales.',
        'back_to_projects' => 'Volver a proyectos',
        'project_deliveries' => 'Entregas del proyecto',
        'project_no_deliveries_yet' => 'Este proyecto todavía no tiene entregas.',

        'delivery' => 'Entrega',
        'blocked' => 'Bloqueada',
        'corrected_and_released' => 'Corregida y liberada',
        'corrected_status' => 'Corregida',
        'submitted' => 'Entregada',
        'late' => 'Fuera de plazo',
        'available' => 'Disponible',

        'submitted_on' => 'Entregado el',
        'file' => 'Archivo',
        'grade' => 'Nota',
        'teacher_comment' => 'Comentario del profesor',
        'phase_corrected_not_released' => 'Esta fase ya fue corregida, pero todavía no ha sido liberada por el profesor.',
        'waiting_teacher_validation' => 'Esperando validación del profesor para desbloquear esta entrega.',
        'view_student_submissions' => 'Ver entregas de alumnos',
        'upload_zip' => 'Subir ZIP',
        'view_sent_file' => 'Ver archivo enviado',
        'delivery_not_available_yet' => 'Esta entrega no está disponible todavía.',
        'project_updated_successfully' => 'Proyecto actualizado correctamente.',
        'edit_project_desc' => 'Modifica el título y la descripción del proyecto.',
        'project_id' => 'ID proyecto',
        'modify_project_data' => 'Modificar datos del proyecto',
        'cancel' => 'Cancelar',
        'project_corrections' => 'Correcciones del proyecto',
        'project_corrections_desc' => 'Gestiona las entregas recibidas y corrige desde una sola vista.',

        'invalid_student_submission' => 'Entrega de estudiante no válida.',
        'grade_required' => 'La nota es obligatoria.',
        'grade_must_be_numeric' => 'La nota debe ser numérica.',
        'grade_range_0_10' => 'La nota debe estar entre 0 y 10.',
        'submission_not_belong_project' => 'La entrega indicada no pertenece a este proyecto.',
        'submission_corrected_released_success' => 'Entrega corregida y fase liberada correctamente.',
        'submission_corrected_next_locked' => 'Entrega corregida correctamente. La siguiente fase sigue bloqueada.',

        'no_student_submissions_project_yet' => 'Todavía no hay entregas enviadas por alumnos en este proyecto.',
        'phase' => 'Fase',
        'pending_plural' => 'Pendientes',
        'corrected_plural' => 'Corregidas',
        'released_plural' => 'Liberadas',

        'submission_date' => 'Fecha de entrega',
        'view_download_file' => 'Ver / descargar archivo',
        'view_full_phase' => 'Ver fase completa',
        'current_correction' => 'Corrección actual',
        'comment' => 'Comentario',
        'update_correction' => 'Actualizar corrección',
        'correct_submission' => 'Corregir entrega',
        'grade_out_of_10' => 'Nota /10',
        'correction_comment_placeholder' => 'Escribe observaciones, mejoras o feedback para el alumno',
        'release_next_delivery' => 'Liberar siguiente entrega',
        'save_correction' => 'Guardar corrección',
        'invalid_delivery' => 'Entrega no válida.',
        'delivery_not_found' => 'Entrega no encontrada.',
        'delivery_required_fields' => 'Título, descripción y orden son obligatorios.',
        'invalid_deadline' => 'La fecha límite no es válida.',
        'delivery_updated_successfully' => 'Entrega actualizada correctamente.',
        'delivery_order_already_exists' => 'Ya existe otra entrega con ese orden dentro de este proyecto.',
        'delivery_update_error' => 'Error al actualizar la entrega',

        'edit_delivery' => 'Editar entrega',
        'edit_delivery_desc' => 'Modifica los datos de esta fase del proyecto.',
        'back_to_deliveries' => 'Volver a entregas',
        'delivery_id' => 'ID entrega',
        'current_order' => 'Orden actual',
        'modify_delivery_data' => 'Modificar datos de la entrega',
        'delivery_title' => 'Título de la entrega',
        'delivery_order' => 'Orden de la entrega',
        'manage_project_deliveries' => 'Gestionar entregas del proyecto',
        'add_sequential_phases' => 'Añade fases secuenciales al proyecto.',
        'create_new_delivery' => 'Crear nueva entrega',
        'delivery_created_successfully' => 'Entrega creada correctamente.',
        'delivery_create_error' => 'Error al crear la entrega',
        'delivery_title_placeholder' => 'Ejemplo: Fase 1 - Diseño inicial',
        'delivery_description_placeholder' => 'Explica qué debe hacer el alumno en esta fase',
        'create_delivery' => 'Crear entrega',
        'created_deliveries' => 'Entregas creadas',
        'no_project_deliveries_yet' => 'Todavía no hay entregas en este proyecto.',
        'created_feminine' => 'Creada',
        'student_deliveries' => 'Entregas de alumnos',
        'student_deliveries_desc' => 'Corrige las entregas de esta fase del proyecto.',
        'student_submission_not_exists_for_phase' => 'La entrega del estudiante no existe para esta fase.',
        'received_deliveries' => 'Entregas recibidas',
        'no_student_deliveries_for_phase_yet' => 'Todavía no hay entregas de alumnos para esta fase.',
        'chapter_not_found' => 'Capítulo no encontrado.',
        'chapter_code_required' => 'El código es obligatorio.',
        'chapter_code_used_by_other' => 'Otro capítulo ya usa ese código.',
        'chapter_code_exists' => 'Ese código ya existe.',

        'edit_chapter' => 'Editar capítulo',
        'create_chapter' => 'Crear capítulo',
        'bilingual_chapter_form' => 'Formulario de capítulo bilingüe.',
        'back_to_list' => 'Volver a la lista',

        'content_es' => 'Contenido ES',
        'content_fr' => 'Contenu FR',
        'theory' => 'Teoría',
        'theory_fr' => 'Théorie',
        'exercise_1' => 'Ejercicio 1',
        'exercise_2' => 'Ejercicio 2',
        'exercise_1_fr' => 'Exercice 1',
        'exercise_2_fr' => 'Exercice 2',
        'title_fr_label' => 'Titre',
        'exercise_not_specified' => 'Error: ejercicio no especificado.',
        'exercise_not_found' => 'Ejercicio no encontrado.',

        'response_saved_successfully' => 'Respuesta guardada correctamente.',
        'write_answer_before_submit' => 'Debes escribir una respuesta antes de enviar el ejercicio.',
        'exercise_sent_completed' => 'Ejercicio enviado y marcado como completado.',
        'could_not_save_response' => 'No se pudo guardar la respuesta',
        'exercise_no_description' => 'Este ejercicio todavía no tiene descripción.',

        'your_solution' => 'Tu solución',
        'write_python_solution_here' => 'Escribe aquí tu solución en Python...',

        'save_draft' => 'Guardar borrador',
        'send_exercise' => 'Enviar ejercicio',

        'exercise_completed' => 'Ejercicio completado.',
        'pending_dot' => 'Pendiente.',

        'student_label' => 'Alumno',

        'how_to_use_page' => 'Cómo usar esta página',
        'exercise_help_1' => 'Escribe tu solución en el editor.',
        'exercise_help_2' => 'Usa “Guardar borrador” para continuar más tarde.',
        'exercise_help_3' => 'Usa “Enviar ejercicio” cuando lo hayas terminado.',
        'exercise_help_4' => 'Al enviarlo, se marcará como completado en tu progreso.',

        'back_to_exercises' => 'Volver a ejercicios',
        'connected_students' => 'Estudiantes conectados',
        'last_activity' => 'Última actividad',
        'no_connected_students' => 'No hay estudiantes conectados.',

        'quiz_deleted_successfully' => 'Quiz eliminado correctamente.',
        'quiz_delete_error' => 'Error al eliminar el quiz',
        'chapter_required' => 'El capítulo es obligatorio.',
        'quiz_title_required' => 'El título del quiz es obligatorio.',
        'quiz_duration_required' => 'La duración es obligatoria.',
        'quiz_updated_successfully' => 'Quiz actualizado correctamente.',
        'quiz_created_successfully' => 'Quiz creado correctamente.',
        'quiz_save_error' => 'Error al guardar el quiz',
        'quiz_load_error' => 'Error al cargar los quizzes',

        'new_quiz' => 'Nuevo quiz',
        'edit_quiz' => 'Editar quiz',
        'create_quiz' => 'Crear quiz',
        'quiz_list' => 'Lista de quizzes',
        'no_quizzes_yet' => 'Todavía no hay quizzes.',
        'quiz_default_description' => 'Quiz del capítulo.',

        'duration_minutes' => 'Duración (minutos)',
        'questions' => 'Preguntas',
        'manage_questions' => 'Gestionar preguntas',
        'confirm_delete_quiz' => '¿Seguro que quieres eliminar este quiz y todas sus preguntas?',
        'inactive' => 'Inactivo',
        'question_not_found' => 'Pregunta no encontrada.',
        'invalid_question' => 'Pregunta no válida.',
        'question_deleted_successfully' => 'Pregunta eliminada correctamente.',
        'question_delete_error' => 'Error al eliminar la pregunta',
        'question_text_required' => 'El texto de la pregunta es obligatorio.',
        'all_options_required' => 'Todas las opciones son obligatorias.',
        'valid_correct_answer_required' => 'Debes indicar una respuesta correcta válida.',
        'question_order_required' => 'El orden de la pregunta es obligatorio.',
        'question_updated_successfully' => 'Pregunta actualizada correctamente.',
        'question_created_successfully' => 'Pregunta creada correctamente.',
        'question_save_error' => 'Error al guardar la pregunta',
        'question_load_error' => 'Error al cargar las preguntas',

        'back_to_quizzes' => 'Volver a quizzes',
        'new_question' => 'Nueva pregunta',
        'edit_question' => 'Editar pregunta',
        'create_question' => 'Crear pregunta',
        'question_text' => 'Texto de la pregunta',
        'option_a' => 'Opción A',
        'option_b' => 'Opción B',
        'option_c' => 'Opción C',
        'option_d' => 'Opción D',
        'correct_answer' => 'Respuesta correcta',
        'explanation' => 'Explicación',
        'no_questions_yet' => 'Todavía no hay preguntas.',
        'confirm_delete_question' => '¿Seguro que quieres eliminar esta pregunta?',

    ],

    'fr' => [
        'question_not_found' => 'Question introuvable.',
        'invalid_question' => 'Question non valide.',
        'question_deleted_successfully' => 'Question supprimée avec succès.',
        'question_delete_error' => 'Erreur lors de la suppression de la question',
        'question_text_required' => 'Le texte de la question est obligatoire.',
        'all_options_required' => 'Toutes les options sont obligatoires.',
        'valid_correct_answer_required' => 'Tu dois indiquer une réponse correcte valide.',
        'question_order_required' => 'L’ordre de la question est obligatoire.',
        'question_updated_successfully' => 'Question mise à jour avec succès.',
        'question_created_successfully' => 'Question créée avec succès.',
        'question_save_error' => 'Erreur lors de l’enregistrement de la question',
        'question_load_error' => 'Erreur lors du chargement des questions',

        'back_to_quizzes' => 'Retour aux quiz',
        'new_question' => 'Nouvelle question',
        'edit_question' => 'Modifier la question',
        'create_question' => 'Créer la question',
        'question_text' => 'Texte de la question',
        'option_a' => 'Option A',
        'option_b' => 'Option B',
        'option_c' => 'Option C',
        'option_d' => 'Option D',
        'correct_answer' => 'Bonne réponse',
        'explanation' => 'Explication',
        'no_questions_yet' => 'Il n’y a pas encore de questions.',
        'confirm_delete_question' => 'Voulez-vous vraiment supprimer cette question ?',
        'quiz_not_found' => 'Quiz introuvable.',
        'invalid_quiz' => 'Quiz non valide.',
        'quiz_deleted_successfully' => 'Quiz supprimé avec succès.',
        'quiz_delete_error' => 'Erreur lors de la suppression du quiz',
        'chapter_required' => 'Le chapitre est obligatoire.',
        'quiz_title_required' => 'Le titre du quiz est obligatoire.',
        'quiz_duration_required' => 'La durée est obligatoire.',
        'quiz_updated_successfully' => 'Quiz mis à jour avec succès.',
        'quiz_created_successfully' => 'Quiz créé avec succès.',
        'quiz_save_error' => 'Erreur lors de l’enregistrement du quiz',
        'quiz_load_error' => 'Erreur lors du chargement des quiz',

        'new_quiz' => 'Nouveau quiz',
        'edit_quiz' => 'Modifier le quiz',
        'create_quiz' => 'Créer le quiz',
        'quiz_list' => 'Liste des quiz',
        'no_quizzes_yet' => 'Il n’y a pas encore de quiz.',
        'quiz_default_description' => 'Quiz du chapitre.',

        'duration_minutes' => 'Durée (minutes)',
        'questions' => 'Questions',
        'manage_questions' => 'Gérer les questions',
        'confirm_delete_quiz' => 'Voulez-vous vraiment supprimer ce quiz et toutes ses questions ?',
        'inactive' => 'Inactif',
        'edit' => 'Modifier',
        'delete' => 'Supprimer',
        'active' => 'Actif',
        'connected_students' => 'Étudiants connectés',
        'last_activity' => 'Dernière activité',
        'no_connected_students' => 'Aucun étudiant connecté.',
        'student' => 'Étudiant',
        'user_not_identified' => 'Erreur : utilisateur non identifié.',
        'exercise_not_specified' => 'Erreur : exercice non spécifié.',
        'exercise_not_found' => 'Exercice introuvable.',

        'response_saved_successfully' => 'Réponse enregistrée avec succès.',
        'write_answer_before_submit' => 'Tu dois écrire une réponse avant d’envoyer l’exercice.',
        'exercise_sent_completed' => 'Exercice envoyé et marqué comme terminé.',
        'could_not_save_response' => 'Impossible d’enregistrer la réponse',

        'chapter' => 'Chapitre',
        'code' => 'Code',

        'statement' => 'Énoncé',
        'exercise_no_description' => 'Cet exercice n’a pas encore de description.',

        'your_solution' => 'Ta solution',
        'write_python_solution_here' => 'Écris ici ta solution en Python...',

        'save_draft' => 'Enregistrer le brouillon',
        'send_exercise' => 'Envoyer l’exercice',

        'exercise_completed' => 'Exercice terminé.',
        'pending_dot' => 'En attente.',

        'student_label' => 'Étudiant',

        'how_to_use_page' => 'Comment utiliser cette page',
        'exercise_help_1' => 'Écris ta solution dans l’éditeur.',
        'exercise_help_2' => 'Utilise “Enregistrer le brouillon” pour continuer plus tard.',
        'exercise_help_3' => 'Utilise “Envoyer l’exercice” quand tu as terminé.',
        'exercise_help_4' => 'Une fois envoyé, il sera marqué comme terminé dans ta progression.',

        'back_to_exercises' => 'Retour aux exercices',
        'dashboard' => 'Tableau de bord',
        'chapter_not_found' => 'Chapitre introuvable.',
        'chapter_code_required' => 'Le code est obligatoire.',
        'chapter_code_used_by_other' => 'Un autre chapitre utilise déjà ce code.',
        'chapter_code_exists' => 'Ce code existe déjà.',

        'edit_chapter' => 'Modifier le chapitre',
        'create_chapter' => 'Créer le chapitre',
        'bilingual_chapter_form' => 'Formulaire de chapitre bilingue.',
        'back_to_list' => 'Retour à la liste',

        'content_es' => 'Contenu ES',
        'content_fr' => 'Contenu FR',
        'theory' => 'Théorie',
        'theory_fr' => 'Théorie',
        'exercise_1' => 'Exercice 1',
        'exercise_2' => 'Exercice 2',
        'exercise_1_fr' => 'Exercice 1',
        'exercise_2_fr' => 'Exercice 2',
        'title_fr_label' => 'Titre',
        'student_deliveries' => 'Remises des élèves',
        'student_deliveries_desc' => 'Corrige les remises de cette phase du projet.',
        'student_submission_not_exists_for_phase' => 'La remise de l’élève n’existe pas pour cette phase.',
        'received_deliveries' => 'Remises reçues',
        'no_student_deliveries_for_phase_yet' => 'Il n’y a pas encore de remises d’élèves pour cette phase.',
        'invalid_delivery' => 'Remise invalide.',
        'delivery_not_found' => 'Remise introuvable.',
        'delivery_required_fields' => 'Le titre, la description et l’ordre sont obligatoires.',
        'invalid_deadline' => 'La date limite n’est pas valide.',
        'delivery_updated_successfully' => 'Remise mise à jour avec succès.',
        'delivery_order_already_exists' => 'Il existe déjà une autre remise avec cet ordre dans ce projet.',
        'delivery_update_error' => 'Erreur lors de la mise à jour de la remise',

        'edit_delivery' => 'Modifier la remise',
        'edit_delivery_desc' => 'Modifie les données de cette phase du projet.',
        'back_to_deliveries' => 'Retour aux remises',
        'delivery_id' => 'ID de la remise',
        'current_order' => 'Ordre actuel',
        'modify_delivery_data' => 'Modifier les données de la remise',
        'delivery_title' => 'Titre de la remise',
        'delivery_order' => 'Ordre de la remise',
        'manage_project_deliveries' => 'Gérer les remises du projet',
        'add_sequential_phases' => 'Ajoute des phases séquentielles au projet.',
        'create_new_delivery' => 'Créer une nouvelle remise',
        'delivery_created_successfully' => 'Remise créée avec succès.',
        'delivery_create_error' => 'Erreur lors de la création de la remise',
        'delivery_title_placeholder' => 'Exemple : Phase 1 - Conception initiale',
        'delivery_description_placeholder' => 'Explique ce que l’élève doit faire dans cette phase',
        'create_delivery' => 'Créer la remise',
        'created_deliveries' => 'Remises créées',
        'no_project_deliveries_yet' => 'Il n’y a pas encore de remises dans ce projet.',
        'created_feminine' => 'Créée',
        'invalid_delivery' => 'Remise invalide.',
        'delivery_not_found' => 'Remise introuvable.',
        'delivery_required_fields' => 'Le titre, la description et l’ordre sont obligatoires.',
        'invalid_deadline' => 'La date limite n’est pas valide.',
        'delivery_updated_successfully' => 'Remise mise à jour avec succès.',
        'delivery_order_already_exists' => 'Il existe déjà une autre remise avec cet ordre dans ce projet.',
        'delivery_update_error' => 'Erreur lors de la mise à jour de la remise',

        'edit_delivery' => 'Modifier la remise',
        'edit_delivery_desc' => 'Modifie les données de cette phase du projet.',
        'back_to_deliveries' => 'Retour aux remises',
        'delivery_id' => 'ID de la remise',
        'current_order' => 'Ordre actuel',
        'modify_delivery_data' => 'Modifier les données de la remise',
        'delivery_title' => 'Titre de la remise',
        'delivery_order' => 'Ordre de la remise',
        'project_corrections' => 'Corrections du projet',
        'project_corrections_desc' => 'Gère les remises reçues et corrige-les depuis une seule vue.',

        'invalid_student_submission' => 'Remise étudiante non valide.',
        'grade_required' => 'La note est obligatoire.',
        'grade_must_be_numeric' => 'La note doit être numérique.',
        'grade_range_0_10' => 'La note doit être comprise entre 0 et 10.',
        'submission_not_belong_project' => 'La remise indiquée n’appartient pas à ce projet.',
        'submission_corrected_released_success' => 'Remise corrigée et phase publiée avec succès.',
        'submission_corrected_next_locked' => 'Remise corrigée avec succès. La phase suivante reste bloquée.',

        'no_student_submissions_project_yet' => 'Aucune remise envoyée par les élèves pour ce projet pour le moment.',
        'phase' => 'Phase',
        'pending_plural' => 'En attente',
        'corrected_plural' => 'Corrigées',
        'released_plural' => 'Publiées',

        'submission_date' => 'Date de remise',
        'view_download_file' => 'Voir / télécharger le fichier',
        'view_full_phase' => 'Voir la phase complète',
        'current_correction' => 'Correction actuelle',
        'comment' => 'Commentaire',
        'update_correction' => 'Mettre à jour la correction',
        'correct_submission' => 'Corriger la remise',
        'grade_out_of_10' => 'Note /10',
        'correction_comment_placeholder' => 'Écris des observations, améliorations ou retours pour l’élève',
        'release_next_delivery' => 'Débloquer la remise suivante',
        'save_correction' => 'Enregistrer la correction',
        'project_updated_successfully' => 'Projet mis à jour avec succès.',
        'edit_project_desc' => 'Modifie le titre et la description du projet.',
        'project_id' => 'ID du projet',
        'modify_project_data' => 'Modifier les données du projet',
        'cancel' => 'Annuler',
        'role_not_allowed' => 'Rôle non autorisé.',
        'invalid_project' => 'Projet non valide.',
        'project_not_found' => 'Projet introuvable.',

        'project_with_deliveries' => 'Projet avec remises séquentielles.',
        'back_to_projects' => 'Retour aux projets',
        'project_deliveries' => 'Remises du projet',
        'project_no_deliveries_yet' => 'Ce projet ne contient pas encore de remises.',

        'delivery' => 'Remise',
        'blocked' => 'Bloquée',
        'corrected_and_released' => 'Corrigée et publiée',
        'corrected_status' => 'Corrigée',
        'submitted' => 'Remise envoyée',
        'late' => 'Hors délai',
        'available' => 'Disponible',

        'submitted_on' => 'Remis le',
        'file' => 'Fichier',
        'grade' => 'Note',
        'teacher_comment' => 'Commentaire du professeur',
        'phase_corrected_not_released' => 'Cette phase a déjà été corrigée, mais elle n’a pas encore été publiée par le professeur.',
        'waiting_teacher_validation' => 'En attente de la validation du professeur pour débloquer cette remise.',
        'view_student_submissions' => 'Voir les remises des élèves',
        'upload_zip' => 'Envoyer le ZIP',
        'view_sent_file' => 'Voir le fichier envoyé',
        'delivery_not_available_yet' => 'Cette remise n’est pas encore disponible.',
        'projects_dashboard' => 'Tableau de bord des projets',
        'projects_dashboard_desc' => 'Vue générale des projets, des phases et des corrections en attente.',
        'no_projects_created_yet' => 'Aucun projet créé pour le moment.',
        'pending_count_badge' => '%d en attente',
        'no_pending' => 'Aucun en attente',
        'phases' => 'Phases',
        'received_submissions' => 'Remises reçues',
        'corrected' => 'Corrigées',
        'released' => 'Publiées',
        'pending_corrections' => 'Corrections en attente',
        'manage_phases' => 'Gérer les phases',
        'edit_project' => 'Modifier le projet',
        'view_corrections' => 'Voir les corrections',
        'project_required_fields' => 'Le titre et la description sont obligatoires.',
        'project_created' => 'Projet créé avec succès.',
        'projects_admin_desc' => 'Crée des projets composés de plusieurs remises séquentielles.',
        'create_project' => 'Créer un projet',
        'project_title' => 'Titre du projet',
        'project_title_placeholder' => 'Exemple : Projet final Python',
        'description' => 'Description',
        'project_description_placeholder' => 'Décris le projet, ses objectifs, ses exigences, etc.',
        'create_project_btn' => 'Créer le projet',
        'created_projects' => 'Projets créés',
        'view_documentation' => 'Voir la documentation',
        'manage_submissions' => 'Gérer les remises',
        'no_projects_yet' => 'Aucun projet pour le moment.',
        'invalid_chapter' => 'Chapitre invalide.',
        'invalid_visibility_value' => 'Valeur de visibilité invalide.',
        'visibility_updated' => 'Visibilité mise à jour.',
        'chapter_deleted' => 'Chapitre supprimé.',

        'chapters_list_desc' => 'Liste des chapitres du cours.',
        'new_chapter' => 'Nouveau chapitre',
        'code' => 'Code',
        'edit' => 'Modifier',
        'deactivate' => 'Désactiver',
        'activate' => 'Activer',
        'delete' => 'Supprimer',
        'confirm_delete_chapter' => 'Es-tu sûr de vouloir supprimer ce chapitre ?',  
        'admin_dashboard' => 'Tableau de bord administrateur',
        'admin_panel' => 'Panneau administrateur',
        'admin_panel_desc' => 'Gère les étudiants, les chapitres, les devoirs, les projets et la progression du cours.',
        'student_panel' => 'Panneau étudiant',

        'students' => 'Étudiants',
        'approved' => 'approuvés',
        'chapters' => 'Chapitres',
        'visible_plural' => 'visibles',
        'homework_projects' => 'Devoirs et projets',
        'homework' => 'devoirs',
        'projects' => 'projets',
        'submissions_progress' => 'Remises / progression',
        'progress_records' => 'enregistrements de progression',

        'manage_chapters' => 'Gérer les chapitres',
        'manage_chapters_desc' => 'Créer, modifier, ordonner et activer les chapitres visibles.',
        'manage_homework' => 'Gérer les devoirs',
        'manage_homework_desc' => 'Créer des devoirs et consulter les remises des élèves.',
        'manage_projects' => 'Gérer les projets',
        'manage_projects_desc' => 'Administrer les projets et leurs remises.',
        'manage_quiz' => 'Gérer les quiz',
        'manage_quiz_desc' => 'Administrer les questions et activités par chapitre.',

        'pending_registrations' => 'Inscriptions en attente',
        'pending_count_suffix' => 'en attente',
        'date' => 'Date',
        'actions' => 'Actions',
        'no_pending_registrations' => 'Aucune inscription en attente.',
        'approve' => 'Approuver',
        'reject' => 'Rejeter',
        'confirm_reject_registration' => 'Es-tu sûr de vouloir rejeter cette inscription ?',

        'latest_students' => 'Derniers étudiants',
        'no_registered_students' => 'Aucun étudiant enregistré.',
        'pending_status' => 'En attente',
        'rejected' => 'Rejeté',

        'chapters_summary' => 'Résumé des chapitres',
        'order' => 'Ordre',
        'title_es' => 'Titre ES',
        'title_fr' => 'Titre FR',
        'visible' => 'Visible',
        'no_chapters_yet' => 'Aucun chapitre pour le moment.',
        'yes' => 'Oui',
        'no' => 'Non',
        'quizzes_by_chapter' => 'Quiz par chapitre',
        'quiz_progress_text' => 'tu peux ici évaluer ta progression.',
        'chapter_quiz_default_desc' => 'Quiz du chapitre.',
        'duration' => 'Durée',
        'best_grade' => 'Meilleure note',
        'no_attempt' => 'Aucune tentative',
        'start_quiz' => 'Commencer le quiz',
        'invalid_quiz' => 'Quiz invalide.',
        'quiz_not_found' => 'Quiz introuvable.',
        'quiz_no_questions' => 'Ce quiz ne contient pas encore de questions.',
        'remaining_time' => 'Temps restant',
        'question' => 'Question',
        'submit_quiz' => 'Remettre le quiz',
        'student' => 'Étudiant',
        'user_not_identified' => 'Utilisateur non identifié.',
        'chapter' => 'Chapitre',
        'hello_user' => 'Bonjour',
        'total' => 'Total',
        'completed' => 'Terminés',
        'pending_lower' => 'en attente',
        'open' => 'Ouvrir',
        'projects_page_desc' => 'Travaux longs avec plusieurs remises séquentielles.',
        'teacher' => 'Professeur',
        'created' => 'Créé',
        'view_project' => 'Voir le projet',
        'no_projects_available' => 'Aucun projet disponible pour le moment.',
        'user_not_found' => 'Utilisateur introuvable.',

        'name_email_required' => 'Le nom et l’e-mail sont obligatoires.',
        'invalid_email' => 'L’e-mail n’est pas valide.',
        'email_already_used' => 'Cette adresse e-mail est déjà utilisée par un autre utilisateur.',
        'fill_three_password_fields' => 'Pour changer le mot de passe, tu dois remplir les trois champs.',
        'password_confirmation_mismatch' => 'Le nouveau mot de passe et sa confirmation ne correspondent pas.',
        'password_min_length' => 'Le nouveau mot de passe doit contenir au moins 6 caractères.',
        'current_password_incorrect' => 'Le mot de passe actuel est incorrect.',
        'profile_updated_successfully' => 'Profil mis à jour avec succès.',
        'profile_update_error' => 'Erreur lors de la mise à jour du profil',

        'my_profile' => 'Mon profil',
        'account' => 'Compte',
        'profile_update_desc' => 'Tu peux ici mettre à jour tes informations personnelles et ton mot de passe.',
        'edit_profile' => 'Modifier le profil',
        'name' => 'Nom',
        'email' => 'E-mail',
        'change_password' => 'Changer le mot de passe',
        'leave_password_blank' => 'Laisse ces champs vides si tu ne veux pas changer le mot de passe.',
        'current_password' => 'Mot de passe actuel',
        'new_password' => 'Nouveau mot de passe',
        'confirm_new_password' => 'Confirmer le nouveau mot de passe',
        'save_changes' => 'Enregistrer les modifications',

        'account_information' => 'Informations du compte',
        'current_name' => 'Nom actuel',
        'current_email' => 'E-mail actuel',
        'role' => 'Rôle',
        'member_since' => 'Membre depuis',

        'tip' => 'Conseil',
        'profile_security_tip' => 'Utilise un mot de passe sûr et une adresse e-mail à laquelle tu as accès pour ne pas perdre ton compte.',
        'profile' => 'Profil',
        'open_menu' => 'Ouvrir le menu',
        'dashboard' => 'Tableau de bord',
        'welcome' => 'Bienvenue',
        'personal_space' => 'Votre espace personnel du cours Python.',
        'logout' => 'Se déconnecter',
        'view_course' => 'Voir le cours',
        'view_course_desc' => 'Accéder à tous les chapitres du cours Python.',
        'practices' => 'Exercices',
        'practices_desc' => 'Résoudre des exercices par chapitres avec solutions.',
        'progress' => 'Progression',
        'progress_desc' => 'Ici, nous afficherons bientôt votre progression enregistrée dans MySQL.',
        'summary' => 'Résumé',
        'connected_user' => 'Utilisateur connecté',
        'course' => 'Cours',
        'python_basic' => 'Python débutant',
        'status' => 'Statut',
        'active_account' => 'Compte actif',
        'language' => 'Langue',

        'course_complete' => 'Cours complet',
        'learn_python_zero' => 'Apprendre Python depuis zéro',
        'course_intro_desc' => 'Cours structuré par chapitres avec des exemples clairs et progressifs.',
        'go_practice' => 'Aller aux exercices',
        'back_dashboard' => 'Tableau de bord',

        'intro' => 'Introduction',
        'installation' => 'Installation',
        'hello_world' => 'Bonjour le monde',
        'variables_types' => 'Variables et types',
        'input_output' => 'Entrée et sortie',
        'operators' => 'Opérateurs',
        'conditions' => 'Conditions',
        'loops' => 'Boucles',
        'lists' => 'Listes',
        'tuples_dicts' => 'Tuples et dictionnaires',
        'functions' => 'Fonctions',
        'strings' => 'Chaînes de caractères',
        'text_files' => 'Fichiers texte',
        'json_intro' => 'JSON',
        'errors_exceptions' => 'Erreurs et exceptions',
        'modules' => 'Modules',
        'oop' => 'Programmation orientée objet',
        'mini_project' => 'Mini projet',

        'intro_text' => 'Python est un langage facile à lire, puissant et très utilisé. Il sert à l’automatisation, au développement web, à l’intelligence artificielle, aux scripts, à la science des données et bien plus encore.',
        'installation_text' => 'Installez Python et vérifiez qu’il fonctionne correctement dans le terminal.',
        'hello_world_text' => 'Le premier programme classique affiche un message à l’écran.',
        'variables_text' => 'Les variables permettent de stocker des données. Python détecte automatiquement le type.',
        'input_output_text' => 'Avec input(), vous demandez des données à l’utilisateur et avec print(), vous les affichez.',
        'loops_for' => 'For',
        'loops_while' => 'While',

        'site_title' => 'Cours Python',
        'login' => 'Se connecter',
        'register' => "S'inscrire",
        'hero_badge' => 'Apprendre en pratiquant',
        'hero_title' => 'Apprends Python pas à pas avec une plateforme claire et pratique',
        'hero_desc' => 'Suis le cours, résous des exercices directement en ligne, réalise des quiz avec minuteur et rends tes projets dans un environnement pensé pour progresser étape par étape.',
        'start_now' => 'Commencer maintenant',
        'already_account' => "J'ai déjà un compte",

        'chapters_count' => 'Chapitres du cours',
        'exercises_count' => 'Exercices pratiques',
        'quizzes_count' => 'Quiz par chapitre',

        'student_dashboard' => "Tableau de bord de l'élève",
        'course_progress' => 'Progression du cours',
        'general_progress' => 'Progression générale',
        'exercises_label' => 'Exercices',
        'quizzes_label' => 'Quiz',
        'average_grade' => 'Note moyenne',
        'next_goal' => 'Prochain objectif',
        'next_goal_text' => 'Terminer le chapitre 10 et envoyer le prochain devoir',

        'features_badge' => 'Ce que propose la plateforme',
        'features_title' => 'Tout en un seul endroit',
        'features_desc' => 'Une expérience claire pour étudier, pratiquer, se tester et suivre sa progression.',
        'feature_course' => 'Cours guidé',
        'feature_course_desc' => 'Contenu organisé par chapitres pour apprendre progressivement.',
        'feature_exercises' => 'Exercices pratiques',
        'feature_exercises_desc' => 'Résous les exercices directement depuis la plateforme et sauvegarde ta progression.',
        'feature_quizzes' => 'Quiz automatiques',
        'feature_quizzes_desc' => 'Évalue-toi avec minuteur, correction automatique et note immédiate.',
        'feature_projects' => 'Projets et devoirs',
        'feature_projects_desc' => 'Dépose tes fichiers, suis le calendrier et consolide tes acquis.',

        'cta_title' => "Commence aujourd'hui ta progression en Python",
        'cta_desc' => 'Crée ton compte, accède au contenu du cours et commence à pratiquer dès le premier jour.',
        'create_account' => 'Créer un compte',
        'account_status' => 'Statut',

        'user_id_not_found' => "ID utilisateur introuvable dans la session.",
        'no_grade' => 'Aucune note',
        'no_activity_recorded' => 'Aucune activité enregistrée',
        'dashboard_load_error' => 'Erreur lors du chargement du tableau de bord',

        'progress_message_100' => 'Cours terminé ! Il est maintenant temps de consolider le tout avec le projet final.',
        'progress_message_75' => 'Très belle progression. Tu es déjà dans la dernière ligne droite du cours.',
        'progress_message_50' => 'Bonne progression. Continue ainsi pour arriver au projet en toute confiance.',
        'progress_message_start' => 'Bon début. Continue à avancer petit à petit.',

        'progress_dashboard' => 'Tableau de bord de progression',
        'python_basic_progress' => 'Ta progression en Python débutant',
        'completed_exercises_count' => '%d exercices terminés sur %d',
        'course_completed' => 'Cours terminé',
        'project_submissions_done' => 'Remises effectuées (projet)',

        'completed_exercises' => 'Exercices terminés',
        'out_of_total' => 'Sur un total de %d',
        'pending_submissions_project' => 'Remises en attente (projet)',
        'pending_to_send_or_complete' => 'À envoyer ou à compléter',
        'active' => 'Actif',
        'account_enabled_to_continue' => 'Compte activé pour continuer',
        'current_course' => 'Cours actuel',
        'course_foundations_final_project' => 'Bases + projet final',

        'quick_access' => 'Accès rapides',
        'my_homework' => 'Mes devoirs',
        'my_homework_desc' => 'Voir les consignes et déposer les remises en ZIP.',
        'my_projects' => 'Mes projets',
        'my_projects_desc' => 'Voir les remises du projet et envoyer des fichiers.',
        'quizzes' => 'Quiz',
        'quizzes_desc' => 'Fais des quiz par chapitre avec minuteur et note automatique.',

        'pending' => 'En attente',
        'pending_submissions_count' => '%d remises',
        'homework_desc' => 'Crée des devoirs et publie des consignes pour tes étudiants.',
        'create_homework' => 'Créer un devoir',
        'homework_required_fields' => 'Le titre et l’énoncé sont obligatoires.',
        'homework_created' => 'Devoir créé avec succès.',

        'title' => 'Titre',
        'statement' => 'Énoncé',
        'deadline' => 'Date limite',
        'create_homework_btn' => 'Créer le devoir',

        'published_homework' => 'Devoirs publiés',
        'no_deadline' => 'Aucune date limite',

        'view_submissions' => 'Voir les remises',
        'confirm_delete_homework' => 'Supprimer ce devoir et toutes les remises ?',
        'no_homework_yet' => 'Aucun devoir pour le moment.',
    ]
];

function t(string $key): string {
    global $translations, $lang;
    return $translations[$lang][$key] ?? $key;
}
?>